sudo: false
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_9d61a4057135_key -iv $encrypted_9d61a4057135_iv -in baskobot-b8cae21c879b.json.enc -out baskobot-b8cae21c879b.json -d
install: 
- echo "No install to run"
deploy:
  provider: gae
  keyfile: baskobot-b8cae21c879b.json
  project: baskobot
