sudo: false
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_9d61a4057135_key -iv $encrypted_9d61a4057135_iv -in baskobot-b8cae21c879b.json.enc -out baskobot-b8cae21c879b.json -d
install:
- curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-225.0.0-linux-x86_64.tar.gz --output gcloud.tar.gz
- tar -xvzf gcloud.tar.gz
- pwd
script:
- pip install nosegae
- nosetests --with-gae --gae-lib-root=~/google-cloud-sdk/platform/google_appengine
deploy:
  provider: gae
  keyfile: baskobot-b8cae21c879b.json
  project: baskobot
  on: 
    branch: master
